# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Julian Steitz
tagline: My personal blog
description: My personal blog, chiefly concerned with (un)natural language processing and Python. Musings about tea and everything else might be included.
url: https://unnlp.com

paginate: 5
name: Julian Steitz

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# SEO
# twitter:
#   username: fredrikaverpil
#   url: https://twitter.com/fredrikaverpil
social:
  name: Julian Steitz

  links:
    #- https://linkedin.com/in/fredrik
    #- https://www.facebook.com/fredrik.averpil
    - https://github.com/timpelplomp

# Custom vars
custom_pages:
  feed: /atom.xml
github:
  url: https://github.com/timpelplomp
  repo: https://github.com/timpelplomp/hyde_current
excerpt_separator: <!--more-->
# google_analytics: UA-70773524-1
hyde_version: 2.1.0
hyde_url: http://hyde.getpoole.com
hyde_repo: https://github.com/poole/hyde
show_related_posts: false
force_https: true

# Comments
comments:
  use_disqus: false
  use_googleplus: false
  # disqus_shortname: ffredrikk
